spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

  jpa:
    generate-ddl: true
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5